### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 48: invalid continuation byte

### ISSUE THREAD

**Issue by dekiel123** [Nineteendo/PVZ2tools#18] opened 2022-10-19 02:11 UTC
This time i have that kind of problem:

```
Failed OBBUnpack: UnicodeDecodeError in G:\PVZ2tools-beta\OBBEdit\Shuttle 1\main.30.com.ea.game.pvz2_shu.obb: 'utf-8' codec can't decode byte 0xe7 in position 48: invalid continuation byte
Traceback (most recent call last):
  File "G:\PVZ2tools-beta\OBBEdit\unpack.py", line 576, in file_to_folder
    archive_extract(file, out, unpack_level, False)
  File "G:\PVZ2tools-beta\OBBEdit\unpack.py", line 503, in archive_extract
    rsb_extract(file, pathout_data, out, unpack_level)
  File "G:\PVZ2tools-beta\OBBEdit\unpack.py", line 435, in rsb_extract
    RSG_NAME = file.read(128).strip(b"\0").decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 48: invalid continuation byte

```

OBB: https://drive.google.com/file/d/16SZHPy6Xh4OcbltWDZXdqNsz6KvOinGH/view?usp=sharing

**Comment by Nineteendo** [comment] 2022-10-19 04:58
I currently only catch errors when extracting the rsg, not when getting info for it. When you have an invalid name, that means the program can crash. I'll do my best to fix it.

**Comment by dekiel123** [comment] 2022-10-19 11:54
I have this error on templates 1-6.
OBBUnpacker v1.2.2c

**Comment by dekiel123** [comment] 2022-11-05 14:03
Hi. Any news about the new version?

**Comment by Nineteendo** [comment] 2022-11-05 14:05
No, nothing new yet. I haven't had time lately because of university.

**Comment by Nineteendo** [comment] 2022-12-04 12:25
There's an alpha available on the discord server.

**Comment by dekiel123** [comment] 2022-12-04 21:50
When I try 5 or 6 there is no error however the folder "main.36.com.ea.game.pvz2_shu" is empty.
When I try 1 or 2 everything is fine, all files are extracted but there is an error [fail.txt](https://github.com/Nineteendo/PVZ2tools/files/10149539/fail.txt)
Obb https://drive.google.com/file/d/18cDscottPx9-fHFaSRBEO2r3pMWO-go6/view?usp=share_link

Overall, thank you for your help and for taking your time to solve my problems :-)

**Comment by Nineteendo** [comment] 2022-12-05 08:25
It crashes on mobile, so I'll have to try on a device with more RAM.

**Comment by Nineteendo** [comment] 2023-01-06 12:29
I now made the program raise an error for this, I might bring it back later with an option.

**Comment by dekiel123** [comment] 2023-01-10 14:56
The new version has a new bug. [fail.txt](https://github.com/Nineteendo/PVZ2tools/files/10383761/fail.txt)
https://drive.google.com/file/d/116GydovqP1_pd4bhGS4VAgR5csoFM5GT/view?usp=sharing

**Comment by Nineteendo** [comment] 2023-01-10 16:35
Well, it's currently working as intended: **the tool will not try to fix obbs that were corrupted by modders, instead an error will be raised**. Because I received significant backlash from modders, I've decided that the tool shouldn't repair the obb by default. (It's not their fault for not mentioning this sooner as this tool is not very widespread) I might add an option for it in the future, but I can't promise anything right now. I'm currently working on making the tool at least somewhat useful for these modders in the form of advanced JSON patching.

**Comment by Nineteendo** [comment] 2023-01-10 16:37
This feature is planned for release 1.4.0. I'm currently on v1.2.2c so that's still far away. Release 1.3.0 remains the priority.

**Comment by Nineteendo** [comment] 2023-02-12 10:09
OK, moving it back to v1.3.0

**Comment by Nineteendo** [comment] 2023-02-16 11:21
Working again.

**Closed by Nineteendo** 2023-02-16 11:21 UTC
Labels: bug
