### ISSUE TITLE
Pack RSB

### ISSUE THREAD

**Issue by harumatool-admin** [Nineteendo/PVZ2tools#29] opened 2022-12-11 13:12 UTC
Okay when will we get pack RSB function? This will be finished once the owner made the pack.py

**Comment by Nineteendo** [comment] 2022-12-11 13:15
This is a duplicate of https://github.com/Nineteendo/PVZ2tools/issues/21
I'll definitely try to get this implemented, but I don't have much time.

**Closed by Nineteendo** 2022-12-11 13:15 UTC
Labels: duplicate

**Comment by Nineteendo** [comment] 2022-12-11 13:30
I closed it incorrectly, this is a duplicate as I already explained.
