### ISSUE TITLE
Repair Fake Offset

### ISSUE THREAD

**Issue by Tre-VN** [Nineteendo/PVZ2tools#54] opened 2023-02-12 10:16 UTC
Offset FFFFFF can be easily repaired by set the data of the Subgroup rsgp become 0x00 or insert a blank RSGP there. Since it is blank it is useless to have in the game so it doesnt a problem at all.

**Comment by Nineteendo** [comment] 2023-02-12 10:32
Hmm, duplicate of https://github.com/Nineteendo/PVZ2tools/issues/17?

**Closed by Nineteendo** 2023-02-12 10:32 UTC
Labels: duplicate

**Comment by Nineteendo** [comment] 2023-02-12 10:41
If they use a more reasonable offset, it's also possible part of the obb is missing. (That happened to some of my obbs recently, in that case there are really files missing)
How can I distinguish these two cases? I have to somehow figure out which rsgs are real, and which are fake.
In case they "real", but an unused resolution an option to remove these resolutions will be required.
